---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-gateway
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
            patch: |
              - op: add
                path: /spec/loadBalancerClass
                value: "io.cilium/node"
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: k8s-gateway
    domain: "${SECRET_DOMAIN}"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        io.cilium.nodeipam/match-node-labels: "kubernetes.io/hostname in (node-02)"
      externalTrafficPolicy: Cluster
    watchedResources: ["Ingress", "Service"]
    fallthrough:
      enabled: true
