---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p"
