apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:pPKJKoykQ3OLCvuFqKT9uEH0MK+sCsHnIvWYF5JbBT+jjHwj,iv:ai7sYb+qLCozwZ4eksnfZZyOdRDclrEyEKoHD5XlldE=,tag:iIJGazVXEt4+F4dSdVlV8Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:cggPaJ0wnPaLvFQIB4Y24M0RKV9TFk/CHh/Nks+MlD8PvbExtYzKNUTzCfvprCjazHo+smcnXdCCuxIbUO/cn9gqILp3qDOEpYMFaPc3eLWkABpV+W6iMyXaY1C9kAcrrNcDWRhTjhzfTXMt7NasJxk5N5RqQtFix2deffyZ03v/FiH/xUXggTYgTyt4l9YmuOmw1gd3eXZuKOifkNA2ZW+s3O2Cp9xiv63uFBar1A==,iv:7wgM2QEa1ueuwrvUZrmbRuA6GYlXDuIFsMnrGwWCVtQ=,tag:bE2MdkdZSp6aguoimMnT2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbGVReStFOE5pdHV0MlU1
            elZjem1OTG5RVFlXVXlGcXNCZCtacmphQ3dJCm80dW1ubVBuM3ozREdzdUlLRjlL
            NDE1UVBUZXM5NVRzK29QU3BDd2VFRjAKLS0tIDZRdlFidEpxY1Nqc2RBSUF2cjkv
            Snd2TE4zdUJTM1BEYXNZUzl2WkUydTAKHhXac6/6CooPRA85RVzSYRRVImBE1ZW7
            aoSrvdtawYDCcGEVgaOWxJ17L80h5AWvYB93M8khO/PUG11TvxDw/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T23:27:03Z"
    mac: ENC[AES256_GCM,data:aSh+kUmY/k9F6C1MHvPbUhgffBtcclQvmZ246qMjdOOqiFS86qrq/pJMPFZ7cQwH0nR4X+RBl7rkzY0UMoQvx7HlEJFFQp0dD2IeNx7jQWOPFeTco/UKnTXYs0p9HPgFOpG6IyfVFFUofTHFhY/gTv9nGxxqqmDCZfBPtAwvEq4=,iv:lVYO4Rcf4LdHJ2NSF7zzuGEEIf4mnHrIJ4jmoIs2L/c=,tag:GDehbhqhTLToAfoaxVPQ7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
