apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:O0jlA7yWa13+bIS9IAYbIAGAJRmoSP6nbYh5Zy/jYMFjahFb,iv:IjqQ1w7j7Eog83ipDfeuovbTCnH5Cq+XzPbSZXUwhQw=,tag:0+T2h3cYy1vZ+IZQHwZG1w==,type:str]
    credentials.json: ENC[AES256_GCM,data:CztUm8ddSb5Xw1xwfoyAukwasEvlHOOUZWjmixbTZ8r+piEH9AsuHLkK0BgACtGvaX5Y++9Gl6KeHXWLnBZr0NRq00fGcO64UrQFVOLkQE3x8xP+up8mURPCcNUVdUJEkJSlwP93VPXz4/6SJ9L6ecsXj400X9dkpKMHGQtoG6F1Qpo2LsX7yMGOScFfP1+PjejD5GSkvj96jNjzZO6pqSf79Cpz3v1N33TEl7jDXQ==,iv:DtBxnDlGr20SYGKPp1WflhJJuw4usNeasx1Eo6znrNs=,tag:/2/RYmlPOJ7ohSGFeaq18Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUlh5QjhqM1RsZFREamRK
            MXVkQmZza3FkMEFNTUw1V0RFR0VEVVQ2WHhFCklxbHBLT0lPanBLQ1hpaC9IU0I4
            RlRMTnhCSUdjWHh3RWxWY0tlTVN4UkEKLS0tIDc2Q0xGdHlZemgySGtiVHhvNGV5
            ZzJ2d2pvNEJDcWppKzc3WXJFb2Y2R28KRfC9N+zLMk+2ESaPHa7JoZtEUImxnWFU
            17HNb0BWvpIWmA/tR4PS84N+tesG5+3JDw4xxuOUgcFvL9o7cp/Kyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T18:29:37Z"
    mac: ENC[AES256_GCM,data:ZTrP5IhRzbahQ4hEJlQdBSETOX5FoPSO9asCqXsZfIy4JTYZuvJSHyZXYtCKeETWMYMx92YwOVdkvxeIgWPqwawSteH8FAY5umAaitE48p9kJvGLNtrApxMYuoGK15kuZtAfYo2qvwBqZIC9be0ydkkv1lPYde8ZyLWC5xw/dJc=,iv:nLNJzap/5LeTZkQ/ggU/gIRJvRg6pBmfUEWOujAuFH8=,tag:TAq/rOW2vzHoAQwPIyNUWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
