apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:31Y8QNgeGU/xa6mTK/vBkjTz0dYmqaCOH+SdzV20k8+UAmBJTV8hMA==,iv:jtS3ysVo2w845Xx6Oznk/XzE0iIwxfG4RYtN+//fs5A=,tag:ZFQTTCTErkXlvcIBG9eZ/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcjVKd3pnMTlRTG45SjZU
            ZXdMSjc3SmNyQzhReFM5Z2tLMmRJeGN3WmdVCnFiN3FabXFJRTNJVmsvOStlVDNa
            SXVKMmFvRFA1bFIxWUM2UkNacUQ0aWMKLS0tIGFZM3c0ZG02aGtQOTVmcEREZjFR
            UjNKTzJPTjJ6b3kvdTQ0dnN5dG4rMmcK0qtYEGpBvGOFcjYOg6SVuavtuGXDzjO6
            Edkhr9T3ICGpRJlQUsdRdjsF/0ka3IklgARcaqHJ3EZQSlyJftrERA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T14:52:26Z"
    mac: ENC[AES256_GCM,data:/QBYJBC58WgyszkKDG/rnuJ5WmjDmmhNNySjUZdEbbI9oVV4GwGchkpVesoi3IyIOfe3IjjzTa0uYbZpd10Frfmuis74UkJBHvgkmAXjt2f60PDadAIv6X1hhCCKHHNNQC6iKfItQOdLOTvV/KXrOFQGg5TG8uLBJ+jLvwO9WCU=,iv:F5qXFpV98mXFV9Xp2/33LaCmKY4OBvxHYUguKf4z9dw=,tag:KiJKo+CB4C+ztNiNRdLw0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
