apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:wgz42tlyxBAxwjXJSK24UU80NUESYQFToyDSOn+znGM9awT7xEI5jQ==,iv:mcOPg01X9NGn4nRRnCOXgaaVwmyajcLtEAkuTGbLN1g=,tag:4OCozFQcuz/USmLuX+V93A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdmR2Y2JoL1FJYUoyWXEv
            ZHFpVFhtajY0bHQ4blc0emFlOTF3U0k2S0VJCmp3Qk5Wc1hzaHhSMk9UR3YvQ2RE
            aVFhZDdwN1ZZREhNSjZKbUJLeWk2MU0KLS0tIEZQRm5mbFhjdmVTN1B0TGdmMUJn
            VkdmT1JYdkZ5UHVRbSs2Mm44blpjMXMK84EqSW0pGElmlnXKOzOXyimCijsUjYhm
            1RExD+dj5hZ9EtRgCxHC0ZMBun/MJ1MBA14YFqIvUrWO9Vyuv5zMAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T16:50:39Z"
    mac: ENC[AES256_GCM,data:hRfu+Z/yci9CvyzB7k+Thhhk04DEPbHUcWGK3nqG+p0uBu0YDAIxAmleVTBqxRN2QRYMHggMmP96zDI3v/3BRLSYrBsf2d53EuTeZjqumaZmZmzzf/+fLeah5JqkarxPydctuNgLKREGtEXsEDc7dkVvvbWqtiK4F81/cVoNidI=,iv:kBwA/NqlEN16uIc12a+lTzD4jST6aj3No85pA15pLz8=,tag:5SvAjJlIJVqYi23zVPzSSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
