apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kBiYzwC0bdja,iv:c4zjn4ElDn9DVN3RZp1M0j/rUhzWvH/09u3l14TkQt8=,tag:j4KCJ1d56hWWVc5+aPmUUQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:KoQCcGqPgmE6yMA7i+uL,iv:XdgyX95Y69fLYXdIzzoMJ0lavpxq2dNkq+UgR2VgL/I=,tag:vrtHel0uj2FPyJAPe0Ag7w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Q9r0/PQ2cVSWDAWDualrM9h0A/gzdbS5Qy9d807ULLcHXumk,iv:Htf3TfB/4UUTAdUirXd9saD441NOPvTcu1Q3cpMuiE0=,tag:ps3kwaf7tLxTdsMWByRNpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPODE3aGJJOG4vS3NXQjFG
            RUNvUjZjOExybldIZVZqYTdzaFF1NXlLaEZ3ClFSczFJTklObXp2RFh1L09hZjFB
            VXFPZThSK1FmTVFLZm1CZDhyNGlZZ28KLS0tIEtNdCtwb2lKVU9sUXhtQUdtSG9s
            TU1SakJpaG5ORm0yZ0g3dnpoOWdqY2MKW3eJZsrW9HGoZEbKdPgxdwY2/4c7dUru
            M8cjItZYYO/gCXO4efGAnwpu66n+vCng9BRTD8K06F0lwZyaiAC1Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T21:46:44Z"
    mac: ENC[AES256_GCM,data:Giubflh2tcNg5Z6kUDdPeh3OoxyHxltimYnrhm8F/Y9bD8KWDcnpbWP5c82Q1vE0jmcWXLNoT+NDeehvRXMcx+ygk4P1C/U7GntFfeTEX8mwEr1DmXgSkPxju/H4xapY7Wi8FFluZy6QjbxzxL7IAbZdEpe01Gt0FLAC3WXTyl8=,iv:Mw/kxqeqxHY+uo4Q3KuWpPsiCJl8sjHhnJ2tZjoSXfg=,tag:KMHC/V8ZNAzvglkWCI+1uQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
