apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dUklbiofcUU2,iv:RHPb0T/ZRgFGsv2JwkASQEjgonHKRKgJ4hyJHYkF5kU=,tag:MC1xeBqwNbZYaT4N2hlSmQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:i/AhxbF7mnzBSCVKtW8X,iv:HNcinBs+BrRFIyfbHPEQCPcG2uUdkVQAsloW4f3s3KA=,tag:OC97hAKkMZJG+C+gXZ8W1Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:3ierh/hXq0tc0Hy0QMxG3Ad95+Ox6Vui8GJ4T1if1syHwYcT,iv:37t+cWKPRSiAtrNOZlCyfpc5u3cO97awxkZ0iqwsbYg=,tag:VP7ESVqZjhCiRFEiSzsiUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTUowQUs5LzBNNkZ3THcw
            eWFPR0d4azhtOVVMVysrNTN0SUYzYk9jSEVzCndXSk1aT3J4aHU0ckplQlVjcStu
            NHpoekg1MDFxU2wzRDdGQXpzYTRwemMKLS0tIHo1OTVLdFhTcWFaT2F4Y2IwbFdN
            cHdFUjFhY1J5OEttRFYxcTV2bE9IMDAKrWei1U9mv3sf3qYDAmJWQqEpkyGry8rQ
            0anJuSYyOMTBuMH5bgITUQ8HaQr0pjPjGMQR49PYkgVAjL2nWJwWgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T16:54:01Z"
    mac: ENC[AES256_GCM,data:xzqKoMeXyGB1lux4/HAoMw73P4bTHyB9fyzKfLMHXyO402xfRPGQ2BbaYNRIHpsD1FE4S4TU2CupYC3yQOOmBZiHcn0CsKj3/U/jr88cAv/SJzDiFklgOO88zOR+ooLpJ8M66zIF/UKx9qUBv4Z6KZzaWJFyrb+xKRXxe/IgrUs=,iv:7MA4RSRT86Y8xgAvXeC0J0e1vFzGG89O7ForPziy668=,tag:seNiDvebEOV1ldsXgUNCxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
