apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/AswfXRu6PR2,iv:V7IimgkooH9o9VY5C+1BPUPbgU1sEmTGYtm/MCqaiuk=,tag:28Cz1ALvsfDZmQQ45/niSg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:DDn/J3DDaR0BIiD3uCmW,iv:/sm2FHQD6PtjF1GcE3pi/jGLHnSLKRPVDsM1qUN/v/4=,tag:WOVDaluKdww2YiN895Ur2w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0kbiffn71Zd+YFtlZPJcwNd7G6RXtDtblWoOcCkTadEj+RYK,iv:iXwXEJxKo7GLkjRP9YMO6ZECs51GSkbPOmWr74hLnDg=,tag:gxJHV8cBQTT08b+dBPmUsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVVQ3dWUvMUEvT211L3pE
            MERVQldGRGVvempEcU9aYkFweWNnZGVrdlFvClZiUWdpNWpiaGd6ZHh6U2hvbU9s
            L2JjZFArVlU3dFIwbi9DMkFRRVA3ODQKLS0tIEdwcUs5TDVoc2J4ZHlkcUFQZDA1
            dHlUQWJKc01na0cySEoxc29FNHJhcDgKIksqAjaKkiB1+cXRdUUUHXc/NxaVNp3j
            2ChBhiI4292rgYXu+eBuciAiyTYpL92oGX7S11zNJs2VPeiFMwd8xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T21:51:20Z"
    mac: ENC[AES256_GCM,data:G92UdnZmdl/enVYW04tCauAmVJMcIaJDep9aiub3Kg+F0iWYe6CgeMlMnukA2Cci6qN+DaauhXB9Mk0lcg1idjbIhFcjoUV3ulinQQkP2pJZyFBLyDt53qFQ9thHtVZIjIQp7deQy28xLrGF3fKOYvu1lcOsopmqnL0u3nnO1hA=,iv:3LW3blW+EEvAVLiJCyIs2sIBNXmdp4THbsOOUR0Dq1w=,tag:PZ1d+caeMKTDdpqt/1R9lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
