apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:y6HWnwMi4gZTfCeQf+FtPsfIohvkSwMNhb9XbUuYHd4=,iv:1WYH23opjuw4yMp7+zK3nkwQWRg/LJoFw8NleLRaslY=,tag:fIhmO+adaJx+KqzyHrjhxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdnN4OGY5OFFyT0NQT1ZG
            dm1leW43QytzcXM5aExJU2l1Z0hOVHpXVzNRClRISmJNb285RjZFcENUU0o2dGcr
            bUZrRlI4OUVJQ3gxWFZtLzJhNWFlWHMKLS0tIHZ3d29icGl2SzJscUR1anhSNHlT
            dmlLQkV6VGtQOGtFMTBwdUVUNXVOUHcKbkJrITV7Vcz4Gzt+JWob46mJYrMlZJQw
            iwWjQMHgczGNvBM4nNVaAB3KwVtpF3hKMp+WeA3UpMGV9P3aOKOD3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T14:52:26Z"
    mac: ENC[AES256_GCM,data:Sbvsx9VryO7ilD3DunDHoaq4yT6qeN5YRBPI/JsoC04ZclvM4yDH4seCZ0/eXZNIRTNdh8zh+156nbJ2u2cVZyFn07jC8JxSQy2PcK1YkC+JnS9RTqdH94XcaXbQcZCC2XrkADg8rBNx6zFjjeWhNslvmHaccKQNOrmkgXO7Hho=,iv:b+a+0lp/CQ1fjoLPTm5hb52+DsZmioBUvpOumDF9aRQ=,tag:VRiglESc3tVAp4LfBs1Ulw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
