apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:rucw80T1Sjx6Cu0oWjySCyMFD+KDa8M9In2jR01X5ng=,iv:uD8eXmPaCCC8SEannZWRal3o4dxs6wb54DhGCTeRu5c=,tag:KcG3nEQm1DdGbNqA1x3XEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeFlXNWVMK1d0a2VsWjZm
            OEgyY3gxSUQzdUxEWGZPTVVVWW9lL2ZkZjFzCmlWdU1lUWtQQVRDOXhRWjNjZ1dF
            TFZ3UUNaZEY5cEdJNGR2S3NYVzc4UFUKLS0tIFQ3VDhwcFJUUW5IMjhPdHYzTFNB
            d3VIWmZwWDhwL01NeitxYzdGSDB4UHcKp0QZxUTxINwG/3cyEgWHigG2BuQJy1HZ
            vh4hLo1Ha8wuGr+f5Qab7FSAqhfzGaOZwTlLK2NaBNe5g4ixYSo8Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T11:02:05Z"
    mac: ENC[AES256_GCM,data:uZg82qjCW+FeMMu1zCCfE55u0IYhbKv8deVKdiKlQWQmw9TAQRfBevZF8K3a1hRb3UXVwPRvBsxr7IrQgO0CVbrmga6wBmYm10/aBoXLejkKzKmt0SIr6XVPolcpO6Jf+mr2tfkDvPKQ/1xOG6kpeTlyJi9ASVquNiRWfCsbIUE=,iv:BDqlAl21xoXKH9hN4jvbIlI+sOKUm7JgBh4rTn7FGxk=,tag:MDEaVddaXIFeAKWandySkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
