apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:7dpK45Ty47kwtCmabe+rLoDrrGay8+rAxH8aHF3zUvQ=,iv:gSJXWPKTbv6QC/wGSSfPjer9qF3co6BNaoHQFswsEiY=,tag:5ZfpjiK556G3nXoexCKqiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTL2gyczBjR24xcnJ0Mjhk
            dnRrOTRoazlZdXZIT1EyMkYzRys4SXk1K1JjCjdDRWVMU3VqcWc0dGZxR3QraEVY
            WW9JVzdmaWhLWE5JV1kzQVg0L0hPcGcKLS0tIHYzVWJWeGFac2JPYUcvMEtBcXIw
            NmhjQnBoSjJwazVJdXNXS2tXVHg1eG8KdtIEuXd1NHQiCPAgORIkE3j4nyS/sP8t
            Qr/xu/xLL4rzJP3Xdm+8va+as0F5ScJH1GhpcqHFysosK6e30kI6hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T20:06:25Z"
    mac: ENC[AES256_GCM,data:GL7hfLQyffe7XOBBg06vqTbnRZr7rSbqoPUawwiOWi6abw/OhPV37m3vWvtZ5fFmsmtGuVh2Dd6XU1f+rMql+nGabBxo73Tg+Rw7Qqsuc6e3ja9b7MXI4FJjxhCfz7NK7JQNV9RcznXThW8mtvxTVJou0TfLLUgoCVDfYLjI8h0=,iv:mm3/3tRizTwUXR5GltYiMa8p78uNq0fBWb2MBxBHtag=,tag:FBuNMYepSxxKEi+L+f/bvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
