apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ardVB/JnLP5Le8I8UyfXZdgEhGUxG6zM67vQ9FDtobo=,iv:d9L3e7O3d1Glbs/flzGGgGl/uM4kHxDTI0uPnVtUHPM=,tag:Wtqk59szBinZapOs7BbQsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTDI2ek42UTQ2S0RtOWRB
            MnlpSlpRaFpjVnRrbzhOd3ZZNGVnanFaOVJZClJnNmhzanNwOFBVSmFnVHlzdDRT
            Z1B1RGtMYzkzV1R0cDBuc1ZwaEp2WXMKLS0tIDRtTHBMQndVK3Rjdm43cXJmdEwx
            SUNCN0k5R29xWG1Id3J1TExHR0wvRzgKyRxbbwCqf1wdDM7Dd0P/Q8DQN43s8a9g
            iqi4f3yJ5YjShMXBtCEOJOI+PMHEfm2ZUoM9U0wNdNoi55ga+MDb7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T21:46:43Z"
    mac: ENC[AES256_GCM,data:HCy2bGrWHVLkYUsMi7r9ClaCdoRdRqKmdFl6vP6ajUoIk2EHbTnCk0XdgncBu8m7wc3lRR14bXNgE7YQMLnAD3ugCn2BizAEAqdHw/OOvOPSSK3+LxeOwpAWiohxid3sy6z5yCS7tUhQiJv6zx++mPuQbvHTOXX2An7xu/NBwGs=,iv:hy0sL1S/M42k2kLigR9Kq5vEcwTah3YEWigynSWIVUw=,tag:Y/t+mPuS2YFuv1jxbjzQNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
