---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: vaultwarden
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      tag: 1.32.2-alpine
    env:
      TZ: Europe/Madrid
      DOMAIN: https://vault2.ignic.com
      SIGNUPS_ALLOWED: true
      SHOW_PASSWORD_HINT: false
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        ingressClassName: external
        hosts:
          - host: "vault2.${SECRET_DOMAIN}"
            paths:
              - path: /
    persistence:
      data:
        enabled: true
        retain: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 100Mi
