apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:yS7UBwm4W11cjCmXHM7UTMsI2anJZEXXwaFVYWgQSYCHmsV1LOkTCQ==,iv:2Djn9QajkUFIOhTT0VwNs08vqn9ixGAHTRpgA3CTONg=,tag:FYmhnwX/ubxHuLrz09s4DA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NDRua0w0QVIzTCt1YUxE
            aVNBaHhtMjA3SVpGTk1uYml3ZmhNL3dmazAwCnlMWTcwS2szdnh6L1F2eloxQ3BM
            OVpNMk9ET1MrUGV4M1I1NDZtYWxLWDQKLS0tIHJwQ0ZZRTIzWGR0eERBNWdxZHRj
            VVM5dStrMTZQTGxCQU5WNXcvR0h6MUUK+xyH/M84toAC52vzQpw7OCc80qWyTJU9
            vlcSfNvqVMW1kRxRIYXOZBZLrAKcM4qV/9Zs5lgBAJc0NUoVIosY9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T20:06:25Z"
    mac: ENC[AES256_GCM,data:cqRysTDtn0CB+4ERLaU4QgVUAoDMI9MD8A1vh42E4dKkUTlgCkN96IWJCtutPBEnMrMHLhhwXgThpRLMGlNbSXFyqrC2QYC9h27CEeAYEp9aVAx5qS+dMFeIy4VZzm07MMk02phS921W11CF8RSw7QgKMo5uaLAkdvyyDfFAfRA=,iv:vYvRUlIStVZ/YshE1iRuyH0RiFVmbChIMgxpr+ct8zc=,tag:f52rVm93O5jrEH7h1jBGvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
