apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:YrW4r30YYCovTbf+wNA2gODtSXpYCfVQHfzkuXYkCbChuVBtaRrVxQ==,iv:Df47Oyrz5Bj72xP2zPX7omsTSIlwQdVC+x1FNJ+ygNY=,tag:5cdJbwoBidr+W8eMV0FaAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq23as2r89rm57tjhmqz4fg47g3uasjzmwqfulyhtf255curnvrqhrgs4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT01kK25jSGlJWDlNR1l4
            alZWMDg3V3EzZW5iNjJhNHdwZkQ2T05MQURvCmxyTUdYcGJtQUFQVmdIWnNQNVFK
            dEdHNEFwQ0RaSHVZN2NIczZWTVFLWTAKLS0tIHRyNk43aDFHWFpLTW1zdFdGeUxQ
            dEgyNnVTSnBqVVJPck9ZYytBTEdkbncKXxE2TQKapp0awrMb8T6gaIDNN0HDWhKs
            ZlDbALmrWxDskBmIhG/Ep9nkVh4aZOqYDWwhxeEx0KXjCCxHL9gt8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T20:24:25Z"
    mac: ENC[AES256_GCM,data:3M76IPF/3rgJgtrLTQg/y3dR/WAo+6WAWGSlExrEXCHWGE9dwKfCoOs5TBJrAK06A33zaTuxu6KaLvaU99LN6fYOhbzbXpKKK5twkzEZs//jDjiLxYenb1gvreYXjsPHQrfuQsTShco8qMYVD+ZaBVfZpr/LniZTnyQeemv6SlE=,iv:oqt3TfNRClcnqGtUzqsS0BpYUYb8ffWHwYDzJVJIXeQ=,tag:86nNNRH18z2t+uN71N0Hww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
